name: Task 4 - Composite action Chuck Norris Quote    

# On workflow dispatch
on:
  workflow_dispatch:
# Jobs
jobs:
  fetch-quote:
    name: Fetch quote
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch quote
        uses: ./.github/actions/chuck-norris
        with:
          access-code: '${{ secrets.ACCESSCODE }}'