name: Task 1 - Fix the broken workflow

on:
  push:
    branches:
      - main

jobs:
  task1:
    name: Task 1 - Fix the broken workflow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example-app
    steps:
      - run: actions/checkout@v3
        working-directory: .
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run lint
      - run: npx playwright
      - run: npm test
      - run: npm run build