name: Task 3 - Chuck Norris Quote    

# On workflow dispatch
on:
  workflow_dispatch:
# Jobs

jobs:
  fetch-quote:
    name: Fetch quote
    runs-on: ubuntu-latest
    steps:
      - name: Fetch quote
        uses: fjogeleit/http-request-action@v1
        id: getQuoteResponse
        with:
          url: 'https://api.chucknorris.io/jokes/random'
          method: 'GET'
      - name: Show Response
        id: quote
        run: |
          echo "::set-output name=QUOTE::${{ fromJson(steps.getQuoteResponse.outputs.response).value }}"
      - name: Post quote
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://chuck.alexc.no/api/quote'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "quote": "${{ steps.quote.outputs.QUOTE }}", "accessCode": "${{ secrets.ACCESSCODE }}" }'